### ISSUE TITLE
trouble importing

### ISSUE THREAD

**Issue by vchkan** [sam-cox/pytides#14]
Hi, I'm having some trouble importing pytides, running Python 3.6.0 on 64 bit Anaconda.
Anyone else run into this?

```
>>> import pytides
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\pytides\__init__.py", line 1,
 in <module>
    import tide
ModuleNotFoundError: No module named 'tide'

```

**Comment by vic1309** [comment]
I'm facing this issue too, vchkan. Did you solve it?

**Comment by vchkan** [comment]
Hi vic, got it working with Anaconda Python 2.7.

**Comment by jonnekleijer** [comment]
Hi Vic, Looks like the code is made for Python 2.(7). The relative import does not work in python 3.6 (e.g. "import nodal_corrections" as nc should be "from pytides import nodal_corrections as nc" in constituent.py). Also "reduce" is not used in Python 3, and should then be replaced by functools.reduce(), however  for loop is more readible.

**Comment by vic1309** [comment]
Nice! With these corrections should pytide start working?

Em segunda-feira, 14 de agosto de 2017, Jonne Kleijer <
notifications@github.com> escreveu:
> Hi Vic, Looks like the code is made for Python 2.(7). The relative import
does not work in python 3.6 (e.g. "import nodal_corrections" as nc should
be "from pytides import nodal_corrections as nc" in constituent.py). Also
"reduce" is not used in Python 3, and should then be replaced by
functools.reduce(), however for loop is more readible.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/Vt-BkekEmNrV4ek6jollb9J6JBUCfBZ_TiTTh1uU90S17JfEvWb9BXuUA4IdNmVdRe4o37PDDiIfthM7E7sMo8eozwuvmQ16SoadP4HhzFFDK55GZR1TO6Y7U0fIHw_AB7z4P2Y9cTUbHyfpz1DrKd8-49wAgw=s0-d-e1-ft#https://github.com/notifications/beacon/AKgnUK4QBvHB1z9Qqktcr3dlpqQpHvz8ks5sYDdNgaJpZM4NmCdS.gif>

**Comment by drf5n** [comment]
There are several Python 3 forks:

* https://github.com/drf5n/pytides/tree/py3_v2
* https://github.com/titoconte/pytides
* and a few other forks: https://github.com/titoconte/pytides/network

**Comment by drf5n** [comment]
I get this error

```
% ipython
Python 3.11.4 (main, Jul  5 2023, 08:41:25) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pytides
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import pytides

File ~/anaconda3/envs/junkbuild/lib/python3.11/site-packages/pytides/__init__.py:3
      1 # -*- coding: utf-8 -*-
----> 3 import tide
      4 import astro
      5 import constituent

File ~/Work/pytides/pytides/tide.py:14
     12 from scipy.optimize import leastsq, fsolve
     13 from scipy.linalg import norm
---> 14 from .astro import astro
     15 from . import constituent
     17 def unique(iterable):

ImportError: attempted relative import with no known parent package


```

I installed a different fork of pytides and it worked:

    pip install git+https://github.com/drf5n/pytides.git

```
% ipython                                             
Python 3.11.4 (main, Jul  5 2023, 08:41:25) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pytides

In [2]: dir(pytides.tide)
Out[2]: 
['Iterable',
 'OrderedDict',
 'Tide',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'astro',
 'constituent',
 'count',
 'datetime',
 'filterfalse',
 'fsolve',
 'ifilter',
 'izip',
 'leastsq',
 'norm',
 'np',
 'takewhile',
 'timedelta',
 'unique']

In [3]: 
```
